library("sqldf")
students = read.csv("students.csv")
View(students)
sqldf("select * from students")
sqldf("select count(*) from students")
sqldf("select * from students where marks>70")
sqldf("select * from students where marks<60")
sqldf("select * from students where name='Veer'")
sqldf("select DISTINCT Name from students ")
min(students$marks)
max(students$marks)
sum(students$marks)
nrow(students)
ncol(students)
nrow(students[students$marks==33,])
nrow(students[students$marks>33,])
sqldf("select * from students where marks==12")
